#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Machine Listのみを生成するスクリプト
"""

import random
import sys
import io

# UTF-8エンコーディングを設定
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

def generate_machine_list(count=20):
    """機械リストデータ生成"""
    machines = []
    for i in range(count):
        factory_id = (i % 2) + 1  # 2工場を想定
        machine_no = f"M-{i+1:04d}"
        machines.append(f"({factory_id}, '{machine_no}', 'PRESS', 'admin')")
    return machines

def write_sql_file():
    """SQLファイルを生成（Machine Listのみ）"""
    output_file = 'machine_list_only.sql'
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("""-- Machine List Only
-- Factory Database Portal
-- Generated by generate_machine_list_only.py

SET NAMES utf8mb4;

""")
        
        # Machine List
        f.write("-- ================================================\n")
        f.write("-- Machine List (機械リスト) - 20 records\n")
        f.write("-- ================================================\n")
        f.write("INSERT INTO `machine_list` (`factory_id`, `machine_no`, `machine_type`, `user`) VALUES\n")
        machines = generate_machine_list(20)
        f.write(',\n'.join(machines) + ';\n\n')
    
    print(f"✅ 完了！{output_file}ファイルが生成されました。")

if __name__ == '__main__':
    print("Machine Listデータを生成中...")
    write_sql_file()
