USE factory_db;
-- Import Process Names
-- DAY = 0, SPM = 1
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('CNC', 0, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('ĐÓNG GÓI', 0, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('HẠ NHIỆT', 0, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('LÀM SẠCH SP', 0, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('NHIỆT LUYỆN', 0, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('NHUỘM ĐEN', 0, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('QUAY BÓNG', 0, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('RỬA', 0, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('RỬA SẠCH DẦU', 0, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('RUNG BAVIA', 0, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('RUNG BÓNG', 0, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('RUNG SẠCH', 0, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('RUNG TẨY DẦU', 0, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('RUNG TẨY TRẮNG', 0, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('SƠN', 0, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('IN CHỮ', 0, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('TẨY TRẮNG', 0, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('XI MẠ', 0, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('THỬ ỐC 100%', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('VÉT BAVIA LỖ', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('TÁN', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('XỬ LÝ BAVIA', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('XỬ LÝ CONG', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('XỬ LÝ MẶT PHẲNG', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('XỬ LÝ MÀI CẠNH', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('XỬ LÝ SẠCH SP', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 1/1', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 1/2', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 2/2', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 1/3', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 2/3', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 3/3', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 1/4', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 2/4', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 3/4', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 4/4', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 1/5', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 2/5', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 3/5', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 4/5', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 5/5', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 1/6', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 2/6', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 3/6', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 4/6', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 5/6', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 6/6', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 1/7', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 2/7', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 3/7', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 4/7', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 5/7', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 6/7', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 7/7', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 1/8', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 2/8', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 3/8', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 4/8', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 5/8', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 6/8', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 7/8', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('DẬP 8/8', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('TARO 1/1', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('TARO 1/2', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('TARO 1/3', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('TARO 1/4', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('TARO 2/2', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('TARO 2/3', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('TARO 2/4', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('TARO 3/3', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('TARO 3/4', 1, 'admin');
INSERT INTO process_name_types (process_name, day_or_spm, user) VALUES ('TARO 4/4', 1, 'admin');