INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('HONDA', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('MUSASHI', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('TOSHIBA', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('HARADA', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('MEGGITT', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('TOA', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('JUKI', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('DAIWA', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('SUZUKI', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('Akiba Coating&Technology', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('SUMITOMO', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('AIPHONE', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('NIDEC SEIMITSU', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('SHIOGAI SEIKI', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('TENMA', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('JABIL', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('PARAMOUNT BED', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('GW', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('WERNER', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('SKM', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('KYODENSHA', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('TONG HAI', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('AQUA', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('UENO TEKKO', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('ASTI', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('BELMONT', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('TYS', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('MK.SEIKO', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('FUKUYAMA GOSEI', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('FUJI', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('VMEP', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('FUJIKURA', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('KURABE', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('Công ty TNHH NIDEC ADVANCED MOTOR (VIỆT NAM)', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('FUJIYA', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('BROTHER', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('TIGER', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('TAKAZONO', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('FUJIMAK', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('SOWELL', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('SHENG BANG', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('SHARP(Việt nam)', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('KYOKUTO', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('FUJIKURA JAPAN', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('YUUKI', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('HARADA PHILIPPIN', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('YAMATO PROTEC', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('YAMATO JAPAN', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('THERMTROL', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('TAKAKO', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('EMPRESAS', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('IBEX', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('KATO METAL', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('TOKYO KEIKI', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('OOPARTS', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('TTI', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('TRANSWORLD(USA)', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('SPARTRONICS VIETNAM, INC', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('FOSTER ELECTRIC VIET NAM', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('YAMATO', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('ACTIVE', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('HOÀNG NGUYÊN', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('K.SOURCE', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('NISSEI', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('NISSEI THỦ ĐỨC', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('NISSEI MỸ THO', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('SANKO MOLD', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('VMT', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('AMPHENOL AIR LB', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('TAKARA BELMONT OSAKABELMONT TECHNO KYOTO CORPORATION', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('TAKARA BELMONT CORPORATION SHIGA FACTORY', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('CTY FOCUS LIGHTING', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('D&D', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES (' LIXIL (D\'ADDARIO)', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('D\'ADDARIO', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('NAGAE VN', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('PANASONIC', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('YUWA VIỆT NAM', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('SÀI GÒN PRECISION', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('FURUKAWA', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('MITSUBA', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('SG METAL', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('CÔNG TY TNHH WAKYO MAGALL', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('FUJITSU', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('NIDEC ADVANCED MOTOR ( CHANGZHOU) CORPORATION', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('TANAKA', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('STAR ELEC', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('NAKANO', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('TOWA DENKI', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('SHARP(JAPAN)(ASUE)', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('JYS VN', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('SR SUNTOUR', 1, 'admin');
INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('HANGNAM', 1, 'admin');
