import csv
import os

def read_csv_robust(file_path):
    encodings = ['utf-8-sig', 'utf-8', 'cp932', 'windows-1258']
    for enc in encodings:
        try:
            with open(file_path, 'r', encoding=enc) as f:
                return f.readlines()
        except UnicodeDecodeError:
            continue
    # Fallback
    print(f"Warning: Could not decode {file_path} with standard encodings. Trying cp932 with replace.")
    with open(file_path, 'r', encoding='cp932', errors='replace') as f:
        return f.readlines()

def generate_seed_inserts(customer_csv, employee_csv, output_sql):
    inserts = []
    
    # 1. Customers
    print(f"Processing Customers from {customer_csv}...")
    lines = read_csv_robust(customer_csv)
    reader = csv.DictReader(lines)
    
    inserts.append("-- Customers")
    for row in reader:
        # Header is 'Customer'
        name = row.get('Customer')
        if name:
            name = name.strip()
            safe_name = name.replace("'", "''")
            # INSERT IGNORE to skip duplicates
            sql = f"INSERT IGNORE INTO customers (customer_name, is_active, user) VALUES ('{safe_name}', 1, 'admin');"
            inserts.append(sql)
            
    inserts.append("")
    
    # 2. Employees
    print(f"Processing Employees from {employee_csv}...")
    lines = read_csv_robust(employee_csv)
    reader = csv.DictReader(lines)
    
    inserts.append("-- Employees")
    for row in reader:
        # Headers: FULL NAME, MEMBER ID
        full_name = row.get('FULL NAME')
        member_id = row.get('MEMBER ID')
        
        if full_name and member_id:
            full_name = full_name.strip()
            member_id = member_id.strip()
            
            safe_name = full_name.replace("'", "''")
            safe_id = member_id.replace("'", "''")
            
            # INSERT IGNORE to skip duplicates based on employee_no (UNIQUE)
            # Default password hash (e.g., 'password') or NULL. Using a placeholder hash for now or NULL.
            # Let's use a default hash for '123456' or similar if needed, but for now NULL is safer or just admin's hash?
            # User didn't specify, so I'll leave password_hash NULL for now, or set a default if required.
            # Schema allows NULL password_hash? Yes: `password_hash` VARCHAR(255)
            
            sql = f"INSERT IGNORE INTO employees (employee_no, name, is_active, user) VALUES ('{safe_id}', '{safe_name}', 1, 'admin');"
            inserts.append(sql)

    # Write output
    with open(output_sql, 'w', encoding='utf-8') as f:
        f.write("-- Generated by import_seed_data.py\n")
        f.write("SET NAMES utf8mb4;\n\n")
        f.write("\n".join(inserts))
        f.write("\n")
        
    print(f"Generated {len(inserts)} statements in {output_sql}")

if __name__ == "__main__":
    base_dir = os.path.dirname(os.path.abspath(__file__))
    customer_csv = os.path.join(base_dir, 'シードデータ - Customer.csv')
    employee_csv = os.path.join(base_dir, 'シードデータ - employee.csv')
    output_sql = os.path.join(base_dir, 'import_seed_data.sql')
    
    generate_seed_inserts(customer_csv, employee_csv, output_sql)
