import csv
import os

def generate_product_inserts(csv_path, output_sql_path):
    """
    Reads the product-list.csv and generates SQL inserts for the products table.
    Uses INSERT INTO ... SELECT ... FROM customers WHERE customer_name = ...
    This ensures safety regardless of the actual IDs in the database.
    """
    
    inserts = []
    
    lines = []
    try:
        with open(csv_path, 'r', encoding='utf-8-sig') as f:
            lines = f.readlines()
    except UnicodeDecodeError:
        print("UTF-8 failed for CSV, trying CP932 with replace...")
        with open(csv_path, 'r', encoding='cp932', errors='replace') as f:
            lines = f.readlines()

    reader = csv.DictReader(lines)
    
    # Mapping for corrupted/mismatched names to DB names
    CORRECTIONS = {
        'C\ue31eg ty TNHH NIDEC ADVANCED MOTOR (VI?T NAM)': 'Công ty TNHH NIDEC ADVANCED MOTOR (VIỆT NAM)',
        'CﾔNG TY TNHH WAKYO MAGALL': 'CÔNG TY TNHH WAKYO MAGALL',
        'HOﾀNG NGUYﾊN': 'HOÀNG NGUYÊN',
        'NISSEI M? THO': 'NISSEI MỸ THO',
        'NISSEI TH? ﾐ?C': 'NISSEI THỦ ĐỨC',
        'SA`I GO`N PRECISION': 'SÀI GÒN PRECISION',
        'SHARP(Vi?t nam)': 'SHARP(Việt nam)',
        'YUWA VI?T NAM': 'YUWA VIỆT NAM',
        "LIXIL (D'ADDARIO)": " LIXIL (D'ADDARIO)", # Restore leading space
    }
    
    for row in reader:
        customer_name = row.get('customer') or row.get('Customer')
        product_code = row.get('Product') or row.get('product')
        
        if not customer_name or not product_code:
            continue
            
        customer_name = customer_name.strip()
        product_code = product_code.strip()
        
        # Apply corrections
        if customer_name in CORRECTIONS:
            customer_name = CORRECTIONS[customer_name]
        
        # Escape single quotes
        safe_code = product_code.replace("'", "''")
        safe_customer = customer_name.replace("'", "''")
        
        # Generate safe SQL using subquery with duplicate check
        sql = f"INSERT INTO products (product_code, customer_id, is_active, user) SELECT '{safe_code}', customer_id, 1, 'admin' FROM customers WHERE customer_name = '{safe_customer}' AND NOT EXISTS (SELECT 1 FROM products WHERE product_code = '{safe_code}') LIMIT 1;"
        inserts.append(sql)
    
    # Write to output file
    with open(output_sql_path, 'w', encoding='utf-8') as f:
        f.write("-- Generated by import_product_list.py\n")
        f.write("-- Uses name-based lookup and checks for duplicates (NOT EXISTS)\n")
        f.write("SET NAMES utf8mb4;\n\n")
        f.write("\n".join(inserts))
        f.write("\n")
        
    print(f"Generated {len(inserts)} inserts in {output_sql_path}")

if __name__ == "__main__":
    base_dir = os.path.dirname(os.path.abspath(__file__))
    product_csv_path = os.path.join(base_dir, 'product-list2.csv')
    output_sql_path = os.path.join(base_dir, 'import_products.sql')
    
    print(f"Reading products from: {product_csv_path}")
    generate_product_inserts(product_csv_path, output_sql_path)
