-- Machine List Only
-- Factory Database Portal
-- Generated by generate_machine_list_only.py

SET NAMES utf8mb4;

-- ================================================
-- Machine List (機械リスト) - 20 records
-- ================================================
INSERT INTO `machine_list` (`factory_id`, `machine_no`, `machine_type`, `user`) VALUES
(1, 'M-0001', 'PRESS', 'admin'),
(2, 'M-0002', 'PRESS', 'admin'),
(1, 'M-0003', 'PRESS', 'admin'),
(2, 'M-0004', 'PRESS', 'admin'),
(1, 'M-0005', 'PRESS', 'admin'),
(2, 'M-0006', 'PRESS', 'admin'),
(1, 'M-0007', 'PRESS', 'admin'),
(2, 'M-0008', 'PRESS', 'admin'),
(1, 'M-0009', 'PRESS', 'admin'),
(2, 'M-0010', 'PRESS', 'admin'),
(1, 'M-0011', 'PRESS', 'admin'),
(2, 'M-0012', 'PRESS', 'admin'),
(1, 'M-0013', 'PRESS', 'admin'),
(2, 'M-0014', 'PRESS', 'admin'),
(1, 'M-0015', 'PRESS', 'admin'),
(2, 'M-0016', 'PRESS', 'admin'),
(1, 'M-0017', 'PRESS', 'admin'),
(2, 'M-0018', 'PRESS', 'admin'),
(1, 'M-0019', 'PRESS', 'admin'),
(2, 'M-0020', 'PRESS', 'admin');

