-- Sample PO Data (200 records)
-- 様々なパターンを確認できるように、納期を分散させて作成
-- 遅延（過去）、警告（今日+2日まで）、正常（+5日まで）、将来

SET NAMES utf8mb4;

-- 既存の製品IDを確認して、存在する製品IDに対してPOを作成
-- ここでは product_id 1-10 が存在すると仮定

-- ========================================
-- 遅延パターン（過去の納期）- 50件
-- ========================================

-- 1週間前の納期
INSERT INTO `po` (`po_number`, `product_id`, `delivery_date`, `date_receive_po`, `po_quantity`, `is_delivered`, `user`) VALUES
('PO-PAST-001', 1, DATE_SUB(CURDATE(), INTERVAL 7 DAY), DATE_SUB(CURDATE(), INTERVAL 14 DAY), 5000, FALSE, 'admin'),
('PO-PAST-002', 2, DATE_SUB(CURDATE(), INTERVAL 7 DAY), DATE_SUB(CURDATE(), INTERVAL 14 DAY), 8000, FALSE, 'admin'),
('PO-PAST-003', 3, DATE_SUB(CURDATE(), INTERVAL 7 DAY), DATE_SUB(CURDATE(), INTERVAL 14 DAY), 3500, FALSE, 'admin'),
('PO-PAST-004', 4, DATE_SUB(CURDATE(), INTERVAL 7 DAY), DATE_SUB(CURDATE(), INTERVAL 14 DAY), 6200, FALSE, 'admin'),
('PO-PAST-005', 5, DATE_SUB(CURDATE(), INTERVAL 7 DAY), DATE_SUB(CURDATE(), INTERVAL 14 DAY), 4800, FALSE, 'admin'),
('PO-PAST-006', 1, DATE_SUB(CURDATE(), INTERVAL 6 DAY), DATE_SUB(CURDATE(), INTERVAL 13 DAY), 2000, FALSE, 'admin'),
('PO-PAST-007', 2, DATE_SUB(CURDATE(), INTERVAL 6 DAY), DATE_SUB(CURDATE(), INTERVAL 13 DAY), 3000, FALSE, 'admin'),
('PO-PAST-008', 3, DATE_SUB(CURDATE(), INTERVAL 6 DAY), DATE_SUB(CURDATE(), INTERVAL 13 DAY), 4500, FALSE, 'admin'),
('PO-PAST-009', 4, DATE_SUB(CURDATE(), INTERVAL 6 DAY), DATE_SUB(CURDATE(), INTERVAL 13 DAY), 2500, FALSE, 'admin'),
('PO-PAST-010', 5, DATE_SUB(CURDATE(), INTERVAL 6 DAY), DATE_SUB(CURDATE(), INTERVAL 13 DAY), 3800, FALSE, 'admin'),

-- 5日前の納期
('PO-PAST-011', 1, DATE_SUB(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 12 DAY), 7000, FALSE, 'admin'),
('PO-PAST-012', 2, DATE_SUB(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 12 DAY), 5500, FALSE, 'admin'),
('PO-PAST-013', 3, DATE_SUB(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 12 DAY), 4200, FALSE, 'admin'),
('PO-PAST-014', 4, DATE_SUB(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 12 DAY), 6800, FALSE, 'admin'),
('PO-PAST-015', 5, DATE_SUB(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 12 DAY), 3300, FALSE, 'admin'),
('PO-PAST-016', 1, DATE_SUB(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 11 DAY), 4000, FALSE, 'admin'),
('PO-PAST-017', 2, DATE_SUB(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 11 DAY), 6000, FALSE, 'admin'),
('PO-PAST-018', 3, DATE_SUB(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 11 DAY), 2800, FALSE, 'admin'),
('PO-PAST-019', 4, DATE_SUB(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 11 DAY), 5200, FALSE, 'admin'),
('PO-PAST-020', 5, DATE_SUB(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 11 DAY), 4100, FALSE, 'admin'),

-- 3日前の納期
('PO-PAST-021', 1, DATE_SUB(CURDATE(), INTERVAL 3 DAY), DATE_SUB(CURDATE(), INTERVAL 10 DAY), 8500, FALSE, 'admin'),
('PO-PAST-022', 2, DATE_SUB(CURDATE(), INTERVAL 3 DAY), DATE_SUB(CURDATE(), INTERVAL 10 DAY), 7200, FALSE, 'admin'),
('PO-PAST-023', 3, DATE_SUB(CURDATE(), INTERVAL 3 DAY), DATE_SUB(CURDATE(), INTERVAL 10 DAY), 3900, FALSE, 'admin'),
('PO-PAST-024', 4, DATE_SUB(CURDATE(), INTERVAL 3 DAY), DATE_SUB(CURDATE(), INTERVAL 10 DAY), 5600, FALSE, 'admin'),
('PO-PAST-025', 5, DATE_SUB(CURDATE(), INTERVAL 3 DAY), DATE_SUB(CURDATE(), INTERVAL 10 DAY), 4400, FALSE, 'admin'),
('PO-PAST-026', 1, DATE_SUB(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 9 DAY), 3200, FALSE, 'admin'),
('PO-PAST-027', 2, DATE_SUB(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 9 DAY), 5800, FALSE, 'admin'),
('PO-PAST-028', 3, DATE_SUB(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 9 DAY), 6500, FALSE, 'admin'),
('PO-PAST-029', 4, DATE_SUB(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 9 DAY), 4700, FALSE, 'admin'),
('PO-PAST-030', 5, DATE_SUB(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 9 DAY), 3600, FALSE, 'admin'),

-- 昨日の納期
('PO-PAST-031', 1, DATE_SUB(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 8 DAY), 9000, FALSE, 'admin'),
('PO-PAST-032', 2, DATE_SUB(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 8 DAY), 6700, FALSE, 'admin'),
('PO-PAST-033', 3, DATE_SUB(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 8 DAY), 5300, FALSE, 'admin'),
('PO-PAST-034', 4, DATE_SUB(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 8 DAY), 4900, FALSE, 'admin'),
('PO-PAST-035', 5, DATE_SUB(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 8 DAY), 7500, FALSE, 'admin'),
('PO-PAST-036', 1, DATE_SUB(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 8 DAY), 2200, FALSE, 'admin'),
('PO-PAST-037', 2, DATE_SUB(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 8 DAY), 4300, FALSE, 'admin'),
('PO-PAST-038', 3, DATE_SUB(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 8 DAY), 6100, FALSE, 'admin'),
('PO-PAST-039', 4, DATE_SUB(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 8 DAY), 3700, FALSE, 'admin'),
('PO-PAST-040', 5, DATE_SUB(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 8 DAY), 5400, FALSE, 'admin'),

-- 追加の過去納期（10件）
('PO-PAST-041', 1, DATE_SUB(CURDATE(), INTERVAL 10 DAY), DATE_SUB(CURDATE(), INTERVAL 17 DAY), 4500, FALSE, 'admin'),
('PO-PAST-042', 2, DATE_SUB(CURDATE(), INTERVAL 10 DAY), DATE_SUB(CURDATE(), INTERVAL 17 DAY), 6300, FALSE, 'admin'),
('PO-PAST-043', 3, DATE_SUB(CURDATE(), INTERVAL 9 DAY), DATE_SUB(CURDATE(), INTERVAL 16 DAY), 3800, FALSE, 'admin'),
('PO-PAST-044', 4, DATE_SUB(CURDATE(), INTERVAL 9 DAY), DATE_SUB(CURDATE(), INTERVAL 16 DAY), 5100, FALSE, 'admin'),
('PO-PAST-045', 5, DATE_SUB(CURDATE(), INTERVAL 8 DAY), DATE_SUB(CURDATE(), INTERVAL 15 DAY), 4600, FALSE, 'admin'),
('PO-PAST-046', 1, DATE_SUB(CURDATE(), INTERVAL 8 DAY), DATE_SUB(CURDATE(), INTERVAL 15 DAY), 7800, FALSE, 'admin'),
('PO-PAST-047', 2, DATE_SUB(CURDATE(), INTERVAL 7 DAY), DATE_SUB(CURDATE(), INTERVAL 14 DAY), 5900, FALSE, 'admin'),
('PO-PAST-048', 3, DATE_SUB(CURDATE(), INTERVAL 7 DAY), DATE_SUB(CURDATE(), INTERVAL 14 DAY), 3400, FALSE, 'admin'),
('PO-PAST-049', 4, DATE_SUB(CURDATE(), INTERVAL 6 DAY), DATE_SUB(CURDATE(), INTERVAL 13 DAY), 6600, FALSE, 'admin'),
('PO-PAST-050', 5, DATE_SUB(CURDATE(), INTERVAL 6 DAY), DATE_SUB(CURDATE(), INTERVAL 13 DAY), 4200, FALSE, 'admin');

-- ========================================
-- 警告パターン（今日+2日まで）- 50件
-- ========================================

-- 今日の納期
INSERT INTO `po` (`po_number`, `product_id`, `delivery_date`, `date_receive_po`, `po_quantity`, `is_delivered`, `user`) VALUES
('PO-WARN-001', 1, CURDATE(), DATE_SUB(CURDATE(), INTERVAL 7 DAY), 6000, FALSE, 'admin'),
('PO-WARN-002', 2, CURDATE(), DATE_SUB(CURDATE(), INTERVAL 7 DAY), 4500, FALSE, 'admin'),
('PO-WARN-003', 3, CURDATE(), DATE_SUB(CURDATE(), INTERVAL 7 DAY), 7200, FALSE, 'admin'),
('PO-WARN-004', 4, CURDATE(), DATE_SUB(CURDATE(), INTERVAL 7 DAY), 5300, FALSE, 'admin'),
('PO-WARN-005', 5, CURDATE(), DATE_SUB(CURDATE(), INTERVAL 7 DAY), 3900, FALSE, 'admin'),
('PO-WARN-006', 1, CURDATE(), DATE_SUB(CURDATE(), INTERVAL 7 DAY), 8100, FALSE, 'admin'),
('PO-WARN-007', 2, CURDATE(), DATE_SUB(CURDATE(), INTERVAL 7 DAY), 6400, FALSE, 'admin'),
('PO-WARN-008', 3, CURDATE(), DATE_SUB(CURDATE(), INTERVAL 7 DAY), 4700, FALSE, 'admin'),
('PO-WARN-009', 4, CURDATE(), DATE_SUB(CURDATE(), INTERVAL 7 DAY), 5600, FALSE, 'admin'),
('PO-WARN-010', 5, CURDATE(), DATE_SUB(CURDATE(), INTERVAL 7 DAY), 3200, FALSE, 'admin'),

-- 明日の納期
('PO-WARN-011', 1, DATE_ADD(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 6 DAY), 7500, FALSE, 'admin'),
('PO-WARN-012', 2, DATE_ADD(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 6 DAY), 5800, FALSE, 'admin'),
('PO-WARN-013', 3, DATE_ADD(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 6 DAY), 4200, FALSE, 'admin'),
('PO-WARN-014', 4, DATE_ADD(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 6 DAY), 6900, FALSE, 'admin'),
('PO-WARN-015', 5, DATE_ADD(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 6 DAY), 3700, FALSE, 'admin'),
('PO-WARN-016', 1, DATE_ADD(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 6 DAY), 5100, FALSE, 'admin'),
('PO-WARN-017', 2, DATE_ADD(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 6 DAY), 7300, FALSE, 'admin'),
('PO-WARN-018', 3, DATE_ADD(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 6 DAY), 4600, FALSE, 'admin'),
('PO-WARN-019', 4, DATE_ADD(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 6 DAY), 6200, FALSE, 'admin'),
('PO-WARN-020', 5, DATE_ADD(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 6 DAY), 3400, FALSE, 'admin'),

-- 2日後の納期
('PO-WARN-021', 1, DATE_ADD(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 5 DAY), 8200, FALSE, 'admin'),
('PO-WARN-022', 2, DATE_ADD(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 5 DAY), 6700, FALSE, 'admin'),
('PO-WARN-023', 3, DATE_ADD(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 5 DAY), 4900, FALSE, 'admin'),
('PO-WARN-024', 4, DATE_ADD(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 5 DAY), 5400, FALSE, 'admin'),
('PO-WARN-025', 5, DATE_ADD(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 5 DAY), 7100, FALSE, 'admin'),
('PO-WARN-026', 1, DATE_ADD(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 5 DAY), 3800, FALSE, 'admin'),
('PO-WARN-027', 2, DATE_ADD(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 5 DAY), 6300, FALSE, 'admin'),
('PO-WARN-028', 3, DATE_ADD(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 5 DAY), 5200, FALSE, 'admin'),
('PO-WARN-029', 4, DATE_ADD(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 5 DAY), 4400, FALSE, 'admin'),
('PO-WARN-030', 5, DATE_ADD(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 5 DAY), 7600, FALSE, 'admin'),

-- 追加の警告期間納期（今日、明日、2日後に分散）- 20件
('PO-WARN-031', 1, CURDATE(), DATE_SUB(CURDATE(), INTERVAL 7 DAY), 4800, FALSE, 'admin'),
('PO-WARN-032', 2, CURDATE(), DATE_SUB(CURDATE(), INTERVAL 7 DAY), 5500, FALSE, 'admin'),
('PO-WARN-033', 3, CURDATE(), DATE_SUB(CURDATE(), INTERVAL 7 DAY), 6200, FALSE, 'admin'),
('PO-WARN-034', 4, CURDATE(), DATE_SUB(CURDATE(), INTERVAL 7 DAY), 3600, FALSE, 'admin'),
('PO-WARN-035', 5, CURDATE(), DATE_SUB(CURDATE(), INTERVAL 7 DAY), 7400, FALSE, 'admin'),
('PO-WARN-036', 1, DATE_ADD(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 6 DAY), 4100, FALSE, 'admin'),
('PO-WARN-037', 2, DATE_ADD(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 6 DAY), 6800, FALSE, 'admin'),
('PO-WARN-038', 3, DATE_ADD(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 6 DAY), 5300, FALSE, 'admin'),
('PO-WARN-039', 4, DATE_ADD(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 6 DAY), 3900, FALSE, 'admin'),
('PO-WARN-040', 5, DATE_ADD(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 6 DAY), 7200, FALSE, 'admin'),
('PO-WARN-041', 1, DATE_ADD(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 5 DAY), 5600, FALSE, 'admin'),
('PO-WARN-042', 2, DATE_ADD(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 5 DAY), 4300, FALSE, 'admin'),
('PO-WARN-043', 3, DATE_ADD(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 5 DAY), 6900, FALSE, 'admin'),
('PO-WARN-044', 4, DATE_ADD(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 5 DAY), 5100, FALSE, 'admin'),
('PO-WARN-045', 5, DATE_ADD(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 5 DAY), 3500, FALSE, 'admin'),
('PO-WARN-046', 1, CURDATE(), DATE_SUB(CURDATE(), INTERVAL 7 DAY), 7900, FALSE, 'admin'),
('PO-WARN-047', 2, DATE_ADD(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 6 DAY), 4700, FALSE, 'admin'),
('PO-WARN-048', 3, DATE_ADD(CURDATE(), INTERVAL 1 DAY), DATE_SUB(CURDATE(), INTERVAL 6 DAY), 6100, FALSE, 'admin'),
('PO-WARN-049', 4, DATE_ADD(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 5 DAY), 5800, FALSE, 'admin'),
('PO-WARN-050', 5, DATE_ADD(CURDATE(), INTERVAL 2 DAY), DATE_SUB(CURDATE(), INTERVAL 5 DAY), 4200, FALSE, 'admin');

-- ========================================
-- 正常（緑）パターン（+3日〜+5日）- 50件
-- ========================================

-- 3日後の納期
INSERT INTO `po` (`po_number`, `product_id`, `delivery_date`, `date_receive_po`, `po_quantity`, `is_delivered`, `user`) VALUES
('PO-GREEN-001', 1, DATE_ADD(CURDATE(), INTERVAL 3 DAY), DATE_SUB(CURDATE(), INTERVAL 4 DAY), 5500, FALSE, 'admin'),
('PO-GREEN-002', 2, DATE_ADD(CURDATE(), INTERVAL 3 DAY), DATE_SUB(CURDATE(), INTERVAL 4 DAY), 7200, FALSE, 'admin'),
('PO-GREEN-003', 3, DATE_ADD(CURDATE(), INTERVAL 3 DAY), DATE_SUB(CURDATE(), INTERVAL 4 DAY), 4800, FALSE, 'admin'),
('PO-GREEN-004', 4, DATE_ADD(CURDATE(), INTERVAL 3 DAY), DATE_SUB(CURDATE(), INTERVAL 4 DAY), 6300, FALSE, 'admin'),
('PO-GREEN-005', 5, DATE_ADD(CURDATE(), INTERVAL 3 DAY), DATE_SUB(CURDATE(), INTERVAL 4 DAY), 3900, FALSE, 'admin'),
('PO-GREEN-006', 1, DATE_ADD(CURDATE(), INTERVAL 3 DAY), DATE_SUB(CURDATE(), INTERVAL 4 DAY), 8400, FALSE, 'admin'),
('PO-GREEN-007', 2, DATE_ADD(CURDATE(), INTERVAL 3 DAY), DATE_SUB(CURDATE(), INTERVAL 4 DAY), 5700, FALSE, 'admin'),
('PO-GREEN-008', 3, DATE_ADD(CURDATE(), INTERVAL 3 DAY), DATE_SUB(CURDATE(), INTERVAL 4 DAY), 6600, FALSE, 'admin'),
('PO-GREEN-009', 4, DATE_ADD(CURDATE(), INTERVAL 3 DAY), DATE_SUB(CURDATE(), INTERVAL 4 DAY), 4200, FALSE, 'admin'),
('PO-GREEN-010', 5, DATE_ADD(CURDATE(), INTERVAL 3 DAY), DATE_SUB(CURDATE(), INTERVAL 4 DAY), 7100, FALSE, 'admin'),

-- 4日後の納期
('PO-GREEN-011', 1, DATE_ADD(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 3 DAY), 6800, FALSE, 'admin'),
('PO-GREEN-012', 2, DATE_ADD(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 3 DAY), 5200, FALSE, 'admin'),
('PO-GREEN-013', 3, DATE_ADD(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 3 DAY), 4500, FALSE, 'admin'),
('PO-GREEN-014', 4, DATE_ADD(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 3 DAY), 7600, FALSE, 'admin'),
('PO-GREEN-015', 5, DATE_ADD(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 3 DAY), 3700, FALSE, 'admin'),
('PO-GREEN-016', 1, DATE_ADD(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 3 DAY), 5900, FALSE, 'admin'),
('PO-GREEN-017', 2, DATE_ADD(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 3 DAY), 8200, FALSE, 'admin'),
('PO-GREEN-018', 3, DATE_ADD(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 3 DAY), 4400, FALSE, 'admin'),
('PO-GREEN-019', 4, DATE_ADD(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 3 DAY), 6100, FALSE, 'admin'),
('PO-GREEN-020', 5, DATE_ADD(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 3 DAY), 3300, FALSE, 'admin'),

-- 5日後の納期
('PO-GREEN-021', 1, DATE_ADD(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 2 DAY), 7400, FALSE, 'admin'),
('PO-GREEN-022', 2, DATE_ADD(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 2 DAY), 6500, FALSE, 'admin'),
('PO-GREEN-023', 3, DATE_ADD(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 2 DAY), 5100, FALSE, 'admin'),
('PO-GREEN-024', 4, DATE_ADD(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 2 DAY), 4700, FALSE, 'admin'),
('PO-GREEN-025', 5, DATE_ADD(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 2 DAY), 8300, FALSE, 'admin'),
('PO-GREEN-026', 1, DATE_ADD(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 2 DAY), 3600, FALSE, 'admin'),
('PO-GREEN-027', 2, DATE_ADD(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 2 DAY), 6900, FALSE, 'admin'),
('PO-GREEN-028', 3, DATE_ADD(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 2 DAY), 5400, FALSE, 'admin'),
('PO-GREEN-029', 4, DATE_ADD(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 2 DAY), 4300, FALSE, 'admin'),
('PO-GREEN-030', 5, DATE_ADD(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 2 DAY), 7800, FALSE, 'admin'),

-- 追加の正常期間納期（3-5日後に分散）- 20件
('PO-GREEN-031', 1, DATE_ADD(CURDATE(), INTERVAL 3 DAY), DATE_SUB(CURDATE(), INTERVAL 4 DAY), 5000, FALSE, 'admin'),
('PO-GREEN-032', 2, DATE_ADD(CURDATE(), INTERVAL 3 DAY), DATE_SUB(CURDATE(), INTERVAL 4 DAY), 6400, FALSE, 'admin'),
('PO-GREEN-033', 3, DATE_ADD(CURDATE(), INTERVAL 3 DAY), DATE_SUB(CURDATE(), INTERVAL 4 DAY), 4100, FALSE, 'admin'),
('PO-GREEN-034', 4, DATE_ADD(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 3 DAY), 7200, FALSE, 'admin'),
('PO-GREEN-035', 5, DATE_ADD(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 3 DAY), 5600, FALSE, 'admin'),
('PO-GREEN-036', 1, DATE_ADD(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 3 DAY), 3800, FALSE, 'admin'),
('PO-GREEN-037', 2, DATE_ADD(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 3 DAY), 6700, FALSE, 'admin'),
('PO-GREEN-038', 3, DATE_ADD(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 2 DAY), 4900, FALSE, 'admin'),
('PO-GREEN-039', 4, DATE_ADD(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 2 DAY), 5300, FALSE, 'admin'),
('PO-GREEN-040', 5, DATE_ADD(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 2 DAY), 7500, FALSE, 'admin'),
('PO-GREEN-041', 1, DATE_ADD(CURDATE(), INTERVAL 3 DAY), DATE_SUB(CURDATE(), INTERVAL 4 DAY), 4600, FALSE, 'admin'),
('PO-GREEN-042', 2, DATE_ADD(CURDATE(), INTERVAL 3 DAY), DATE_SUB(CURDATE(), INTERVAL 4 DAY), 6000, FALSE, 'admin'),
('PO-GREEN-043', 3, DATE_ADD(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 3 DAY), 5800, FALSE, 'admin'),
('PO-GREEN-044', 4, DATE_ADD(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 3 DAY), 3400, FALSE, 'admin'),
('PO-GREEN-045', 5, DATE_ADD(CURDATE(), INTERVAL 4 DAY), DATE_SUB(CURDATE(), INTERVAL 3 DAY), 7100, FALSE, 'admin'),
('PO-GREEN-046', 1, DATE_ADD(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 2 DAY), 5200, FALSE, 'admin'),
('PO-GREEN-047', 2, DATE_ADD(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 2 DAY), 4700, FALSE, 'admin'),
('PO-GREEN-048', 3, DATE_ADD(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 2 DAY), 6300, FALSE, 'admin'),
('PO-GREEN-049', 4, DATE_ADD(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 2 DAY), 5500, FALSE, 'admin'),
('PO-GREEN-050', 5, DATE_ADD(CURDATE(), INTERVAL 5 DAY), DATE_SUB(CURDATE(), INTERVAL 2 DAY), 3900, FALSE, 'admin');

-- ========================================
-- 将来パターン（+6日以降）- 50件
-- ========================================

-- 6-10日後の納期
INSERT INTO `po` (`po_number`, `product_id`, `delivery_date`, `date_receive_po`, `po_quantity`, `is_delivered`, `user`) VALUES
('PO-FUTURE-001', 1, DATE_ADD(CURDATE(), INTERVAL 6 DAY), DATE_SUB(CURDATE(), INTERVAL 1 DAY), 6200, FALSE, 'admin'),
('PO-FUTURE-002', 2, DATE_ADD(CURDATE(), INTERVAL 6 DAY), DATE_SUB(CURDATE(), INTERVAL 1 DAY), 4900, FALSE, 'admin'),
('PO-FUTURE-003', 3, DATE_ADD(CURDATE(), INTERVAL 6 DAY), DATE_SUB(CURDATE(), INTERVAL 1 DAY), 7300, FALSE, 'admin'),
('PO-FUTURE-004', 4, DATE_ADD(CURDATE(), INTERVAL 6 DAY), DATE_SUB(CURDATE(), INTERVAL 1 DAY), 5600, FALSE, 'admin'),
('PO-FUTURE-005', 5, DATE_ADD(CURDATE(), INTERVAL 6 DAY), DATE_SUB(CURDATE(), INTERVAL 1 DAY), 4100, FALSE, 'admin'),
('PO-FUTURE-006', 1, DATE_ADD(CURDATE(), INTERVAL 7 DAY), CURDATE(), 8500, FALSE, 'admin'),
('PO-FUTURE-007', 2, DATE_ADD(CURDATE(), INTERVAL 7 DAY), CURDATE(), 5800, FALSE, 'admin'),
('PO-FUTURE-008', 3, DATE_ADD(CURDATE(), INTERVAL 7 DAY), CURDATE(), 6700, FALSE, 'admin'),
('PO-FUTURE-009', 4, DATE_ADD(CURDATE(), INTERVAL 7 DAY), CURDATE(), 4400, FALSE, 'admin'),
('PO-FUTURE-010', 5, DATE_ADD(CURDATE(), INTERVAL 7 DAY), CURDATE(), 7900, FALSE, 'admin'),
('PO-FUTURE-011', 1, DATE_ADD(CURDATE(), INTERVAL 8 DAY), DATE_ADD(CURDATE(), INTERVAL 1 DAY), 5300, FALSE, 'admin'),
('PO-FUTURE-012', 2, DATE_ADD(CURDATE(), INTERVAL 8 DAY), DATE_ADD(CURDATE(), INTERVAL 1 DAY), 6800, FALSE, 'admin'),
('PO-FUTURE-013', 3, DATE_ADD(CURDATE(), INTERVAL 8 DAY), DATE_ADD(CURDATE(), INTERVAL 1 DAY), 4600, FALSE, 'admin'),
('PO-FUTURE-014', 4, DATE_ADD(CURDATE(), INTERVAL 8 DAY), DATE_ADD(CURDATE(), INTERVAL 1 DAY), 7200, FALSE, 'admin'),
('PO-FUTURE-015', 5, DATE_ADD(CURDATE(), INTERVAL 8 DAY), DATE_ADD(CURDATE(), INTERVAL 1 DAY), 3700, FALSE, 'admin'),
('PO-FUTURE-016', 1, DATE_ADD(CURDATE(), INTERVAL 9 DAY), DATE_ADD(CURDATE(), INTERVAL 2 DAY), 6100, FALSE, 'admin'),
('PO-FUTURE-017', 2, DATE_ADD(CURDATE(), INTERVAL 9 DAY), DATE_ADD(CURDATE(), INTERVAL 2 DAY), 5400, FALSE, 'admin'),
('PO-FUTURE-018', 3, DATE_ADD(CURDATE(), INTERVAL 9 DAY), DATE_ADD(CURDATE(), INTERVAL 2 DAY), 7600, FALSE, 'admin'),
('PO-FUTURE-019', 4, DATE_ADD(CURDATE(), INTERVAL 9 DAY), DATE_ADD(CURDATE(), INTERVAL 2 DAY), 4800, FALSE, 'admin'),
('PO-FUTURE-020', 5, DATE_ADD(CURDATE(), INTERVAL 9 DAY), DATE_ADD(CURDATE(), INTERVAL 2 DAY), 6300, FALSE, 'admin'),
('PO-FUTURE-021', 1, DATE_ADD(CURDATE(), INTERVAL 10 DAY), DATE_ADD(CURDATE(), INTERVAL 3 DAY), 5700, FALSE, 'admin'),
('PO-FUTURE-022', 2, DATE_ADD(CURDATE(), INTERVAL 10 DAY), DATE_ADD(CURDATE(), INTERVAL 3 DAY), 7100, FALSE, 'admin'),
('PO-FUTURE-023', 3, DATE_ADD(CURDATE(), INTERVAL 10 DAY), DATE_ADD(CURDATE(), INTERVAL 3 DAY), 4200, FALSE, 'admin'),
('PO-FUTURE-024', 4, DATE_ADD(CURDATE(), INTERVAL 10 DAY), DATE_ADD(CURDATE(), INTERVAL 3 DAY), 6600, FALSE, 'admin'),
('PO-FUTURE-025', 5, DATE_ADD(CURDATE(), INTERVAL 10 DAY), DATE_ADD(CURDATE(), INTERVAL 3 DAY), 3900, FALSE, 'admin'),

-- 11-20日後の納期
('PO-FUTURE-026', 1, DATE_ADD(CURDATE(), INTERVAL 12 DAY), DATE_ADD(CURDATE(), INTERVAL 5 DAY), 7800, FALSE, 'admin'),
('PO-FUTURE-027', 2, DATE_ADD(CURDATE(), INTERVAL 12 DAY), DATE_ADD(CURDATE(), INTERVAL 5 DAY), 5200, FALSE, 'admin'),
('PO-FUTURE-028', 3, DATE_ADD(CURDATE(), INTERVAL 14 DAY), DATE_ADD(CURDATE(), INTERVAL 7 DAY), 6400, FALSE, 'admin'),
('PO-FUTURE-029', 4, DATE_ADD(CURDATE(), INTERVAL 14 DAY), DATE_ADD(CURDATE(), INTERVAL 7 DAY), 4700, FALSE, 'admin'),
('PO-FUTURE-030', 5, DATE_ADD(CURDATE(), INTERVAL 15 DAY), DATE_ADD(CURDATE(), INTERVAL 8 DAY), 8200, FALSE, 'admin'),
('PO-FUTURE-031', 1, DATE_ADD(CURDATE(), INTERVAL 15 DAY), DATE_ADD(CURDATE(), INTERVAL 8 DAY), 5900, FALSE, 'admin'),
('PO-FUTURE-032', 2, DATE_ADD(CURDATE(), INTERVAL 18 DAY), DATE_ADD(CURDATE(), INTERVAL 11 DAY), 6700, FALSE, 'admin'),
('PO-FUTURE-033', 3, DATE_ADD(CURDATE(), INTERVAL 18 DAY), DATE_ADD(CURDATE(), INTERVAL 11 DAY), 4300, FALSE, 'admin'),
('PO-FUTURE-034', 4, DATE_ADD(CURDATE(), INTERVAL 20 DAY), DATE_ADD(CURDATE(), INTERVAL 13 DAY), 7500, FALSE, 'admin'),
('PO-FUTURE-035', 5, DATE_ADD(CURDATE(), INTERVAL 20 DAY), DATE_ADD(CURDATE(), INTERVAL 13 DAY), 5100, FALSE, 'admin'),

-- 21-30日後の納期
('PO-FUTURE-036', 1, DATE_ADD(CURDATE(), INTERVAL 22 DAY), DATE_ADD(CURDATE(), INTERVAL 15 DAY), 6900, FALSE, 'admin'),
('PO-FUTURE-037', 2, DATE_ADD(CURDATE(), INTERVAL 22 DAY), DATE_ADD(CURDATE(), INTERVAL 15 DAY), 4500, FALSE, 'admin'),
('PO-FUTURE-038', 3, DATE_ADD(CURDATE(), INTERVAL 25 DAY), DATE_ADD(CURDATE(), INTERVAL 18 DAY), 8100, FALSE, 'admin'),
('PO-FUTURE-039', 4, DATE_ADD(CURDATE(), INTERVAL 25 DAY), DATE_ADD(CURDATE(), INTERVAL 18 DAY), 5400, FALSE, 'admin'),
('PO-FUTURE-040', 5, DATE_ADD(CURDATE(), INTERVAL 28 DAY), DATE_ADD(CURDATE(), INTERVAL 21 DAY), 7300, FALSE, 'admin'),
('PO-FUTURE-041', 1, DATE_ADD(CURDATE(), INTERVAL 28 DAY), DATE_ADD(CURDATE(), INTERVAL 21 DAY), 4900, FALSE, 'admin'),
('PO-FUTURE-042', 2, DATE_ADD(CURDATE(), INTERVAL 30 DAY), DATE_ADD(CURDATE(), INTERVAL 23 DAY), 6200, FALSE, 'admin'),
('PO-FUTURE-043', 3, DATE_ADD(CURDATE(), INTERVAL 30 DAY), DATE_ADD(CURDATE(), INTERVAL 23 DAY), 5600, FALSE, 'admin'),
('PO-FUTURE-044', 4, DATE_ADD(CURDATE(), INTERVAL 30 DAY), DATE_ADD(CURDATE(), INTERVAL 23 DAY), 7700, FALSE, 'admin'),
('PO-FUTURE-045', 5, DATE_ADD(CURDATE(), INTERVAL 30 DAY), DATE_ADD(CURDATE(), INTERVAL 23 DAY), 4200, FALSE, 'admin'),

-- さらに先の納期
('PO-FUTURE-046', 1, DATE_ADD(CURDATE(), INTERVAL 35 DAY), DATE_ADD(CURDATE(), INTERVAL 28 DAY), 5800, FALSE, 'admin'),
('PO-FUTURE-047', 2, DATE_ADD(CURDATE(), INTERVAL 40 DAY), DATE_ADD(CURDATE(), INTERVAL 33 DAY), 6500, FALSE, 'admin'),
('PO-FUTURE-048', 3, DATE_ADD(CURDATE(), INTERVAL 45 DAY), DATE_ADD(CURDATE(), INTERVAL 38 DAY), 4700, FALSE, 'admin'),
('PO-FUTURE-049', 4, DATE_ADD(CURDATE(), INTERVAL 50 DAY), DATE_ADD(CURDATE(), INTERVAL 43 DAY), 7900, FALSE, 'admin'),
('PO-FUTURE-050', 5, DATE_ADD(CURDATE(), INTERVAL 60 DAY), DATE_ADD(CURDATE(), INTERVAL 53 DAY), 5300, FALSE, 'admin');
